
apiVersion: v1
kind: Service
metadata:
  name: techwithdiwana-fastapi
  namespace: techwithdiwana-llm-prod
spec:
  selector:
    app: twd-llm-fastapi
  ports:
    - name: http
      port: 8000
      targetPort: 8000
