apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: twd-llm-ingress
  namespace: techwithdiwana-llm-prod
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - llm.techwithdiwana.com
      secretName: llm-techwithdiwana-tls
  rules:
    - host: llm.techwithdiwana.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: techwithdiwana-frontend
                port:
                  number: 80
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: techwithdiwana-node-gateway
                port:
                  number: 8080
