apiVersion: apps/v1
kind: Deployment
metadata:
  name: twd-frontend
  namespace: twd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: twd-frontend
  template:
    metadata:
      labels:
        app: twd-frontend
    spec:
      containers:
      - name: frontend
        image: techwithdiwana/frontend:v1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: twd
spec:
  type: ClusterIP
  selector:
    app: twd-frontend
  ports:
  - port: 80
    targetPort: 80
