apiVersion: v1
kind: Service
metadata:
  name: {{ include "frontend-app.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "frontend-app.name" . }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 80
    protocol: TCP
